### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by cpa4001** [AustinHood7/Centz#13]
Add
- Names to links
- add sections (issues, architecture, getting started, etc.)
- Possibly license (but optional)

**Comment by cpa4001** [comment]
Add
- Designs
[Figma Design](https://www.figma.com/file/6ZBvvhyBGC0SRtxnL6WHp7/Centz-Page-Design?node-id=1111%3A913)

**Comment by cpa4001** [comment]
Add labels to Readme resources.
Instead of https://stackabuse.com/post-http-request-in-react/
do [Post Requests in React](https://stackabuse.com/post-http-request-in-react/)
use `[URL NAME](URL)` in readme

**Comment by cpa4001** [comment]
Make links open new tab
Have to update diagrams

**Comment by jakewhanson** [comment]
Update Anchor links (currently not named correctly)

**Comment by jakewhanson** [comment]
ReadMe is up to date (10-27-22)
