### ISSUE TITLE
Add graphs credit to coinranking

### ISSUE THREAD

**Issue by cpa4001** [AustinHood7/Centz#17]
Data provided by [Coinranking](https://coinranking.com/)

**Comment by cpa4001** [comment]
According to https://support.coinranking.com/article/74-can-i-use-the-coinranking-api-for-commercial-purposes , we must add this description below the graphs

**Comment by jakewhanson** [comment]
We can include this credit in a footer with other basic information

**Comment by cpa4001** [comment]
We can add the following to the index.html after root div
> <div class="dataCredit">
      <p>Data provided by <a href="https://coinranking.com/" target={_blank}>Coinranking</a></p>
</div>


OR we can create a footer.
