### ISSUE TITLE
Make search results take the user to the coins page and display the coin api data

### ISSUE THREAD

**Issue by AustinHood7** [AustinHood7/Centz#21]
This takes the result of the form submission and takes the user to the coin page where the selected coin api call is made.

**Comment by jakewhanson** [comment]
Clicking on a card within the sidebar sends a POST request (with coin UUID) to backend, then the Home.js page is updated using the new UUID (see UseEffect/webhook)

This method will be used in nearly the same way but utilizing the search bar instead of the sidebar.
