### ISSUE TITLE
Fix styling cards for coins

### ISSUE THREAD

**Issue by cpa4001** [AustinHood7/Centz#26]
Make a card for a coin with data.
Take a look at this link for inspiration
https://www.coindesk.com/data/

**Comment by cpa4001** [comment]
Added color changing based on value

**Comment by jakewhanson** [comment]
parse coin price and market cap to make rank # in same position on every card

**Comment by cpa4001** [comment]
Team is satisfied with cards and the color of cards based on the change attribute. The styling of the sidebar can be a different issue.
