### ISSUE TITLE
Style the about page

### ISSUE THREAD

**Issue by AustinHood7** [AustinHood7/Centz#33]

**Comment by jakewhanson** [comment]
Basic About-page set up, needs more information and styling
Still includes Top-Coins which needs to be moved to sidebar on home/about page.

**Comment by jakewhanson** [comment]
Jake and Christian bios are included. Top Coins needs to be moved to sidebar.

Could use better styling. Not sure what exactly it needs but it looks kinda odd to me lol

**Comment by jakewhanson** [comment]
About page finished. Top coins have been removed from about page and included in sidebar on home page.
