### ISSUE TITLE
Add react-graphs

### ISSUE THREAD

**Issue by jakewhanson** [AustinHood7/Centz#6]
Add react-graphs to front end - https://www.react-google-charts.com/

**Comment by cpa4001** [comment]
react graphs work, still need to integrate searching, and selection of graph type and/or timeline

**Comment by jakewhanson** [comment]
Graphs work as intended. Need to implement graph options for the user such as timeline (24h, 7-day, 1-month, etc. See coinranking API for timeline availabilities.)

**Comment by jakewhanson** [comment]
Graphs can now change the time period through Axios POST requests.
